#!/bin/sh
# OIS v3 -- core/service.sh
# Daemon registration with the host init system.
#
# Declarative in ois.conf:
#   [service]
#   enable      = true
#   args        = --daemon --config $XDG_CONFIG_HOME/myapp/app.toml
#   description = My daemon
#   restart     = on-failure        # always | on-failure | no
#   after       = network           # network | none
#
# Backends: systemd (system AND user units), launchd (LaunchDaemons /
# LaunchAgents), OpenRC (system only). Detection is runtime; the
# OIS_SERVICE_BACKEND env override exists so the test suite can exercise
# every backend on one machine with PATH-shimmed init tools.
#
# Lifecycle wiring (update.sh / ois.sh):
#   install    -> write unit, enable, start (when enable = true)
#   update     -> stop before the binary swap, start after
#   uninstall  -> stop, disable, remove unit
#   ois service <app> start|stop|restart|status
#
# Limitation, documented: `args` is split on whitespace for launchd's
# ProgramArguments array. Arguments containing spaces need a wrapper
# script. systemd and OpenRC receive the string verbatim.
# ---------------------------------------------------------------------

ois_service_backend() {
    if [ -n "${OIS_SERVICE_BACKEND:-}" ]; then
        printf '%s' "$OIS_SERVICE_BACKEND" ; return 0
    fi
    if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
        printf 'systemd' ; return 0
    fi
    if [ "$OIS_OS" = "macos" ] && command -v launchctl >/dev/null 2>&1; then
        printf 'launchd' ; return 0
    fi
    if command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then
        printf 'openrc' ; return 0
    fi
    printf 'none'
}

# -- Unit file locations ----------------------------------------------
_ois_svc_unit_path() {   # APP -> path of the unit/plist/script
    _sp_app="$1"
    case "$(ois_service_backend)" in
        systemd)
            if [ "$OIS_SCOPE" = "system" ]; then
                printf '/etc/systemd/system/%s.service' "$_sp_app"
            else
                printf '%s/systemd/user/%s.service' "$OIS_XDG_CONFIG" "$_sp_app"
            fi ;;
        launchd)
            if [ "$OIS_SCOPE" = "system" ]; then
                printf '/Library/LaunchDaemons/com.ois.%s.plist' "$_sp_app"
            else
                printf '%s/Library/LaunchAgents/com.ois.%s.plist' "$OIS_HOME" "$_sp_app"
            fi ;;
        openrc)
            printf '/etc/init.d/%s' "$_sp_app" ;;
    esac
}

_ois_svc_ctl() {   # run the init tool, privileged when system scope
    if [ "$OIS_SCOPE" = "system" ] && [ "$OIS_IS_ROOT" != "yes" ]; then
        ois_priv "$@"
    else
        "$@"
    fi
}

_ois_systemctl() {   # systemctl with --user in user scope
    if [ "$OIS_SCOPE" = "system" ]; then
        _ois_svc_ctl systemctl "$@"
    else
        systemctl --user "$@"
    fi
}

# -- Unit generation ---------------------------------------------------
_ois_svc_gen_systemd() {   # APP BIN ARGS DESC RESTART AFTER -> stdout
    printf '# Generated by OIS. Edits are overwritten on update.\n'
    printf '[Unit]\nDescription=%s\n' "${4:-$1}"
    [ "${6:-network}" = "network" ] && printf 'After=network.target\n'
    printf '\n[Service]\nExecStart=%s %s\n' "$2" "$3"
    case "${5:-on-failure}" in
        always)     printf 'Restart=always\n' ;;
        on-failure) printf 'Restart=on-failure\n' ;;
    esac
    printf '\n[Install]\n'
    if [ "$OIS_SCOPE" = "system" ]; then
        printf 'WantedBy=multi-user.target\n'
    else
        printf 'WantedBy=default.target\n'
    fi
}

_ois_svc_gen_launchd() {   # APP BIN ARGS DESC RESTART -> stdout
    printf '<?xml version="1.0" encoding="UTF-8"?>\n'
    printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    printf '<plist version="1.0">\n<dict>\n'
    printf '    <key>Label</key>\n    <string>com.ois.%s</string>\n' "$1"
    printf '    <key>ProgramArguments</key>\n    <array>\n'
    printf '        <string>%s</string>\n' "$2"
    for _gl_a in $3; do
        printf '        <string>%s</string>\n' "$_gl_a"
    done
    printf '    </array>\n'
    printf '    <key>RunAtLoad</key>\n    <true/>\n'
    case "${5:-on-failure}" in
        always|on-failure) printf '    <key>KeepAlive</key>\n    <true/>\n' ;;
    esac
    printf '</dict>\n</plist>\n'
}

_ois_svc_gen_openrc() {   # APP BIN ARGS DESC -> stdout
    printf '#!/sbin/openrc-run\n# Generated by OIS. Edits are overwritten on update.\n'
    printf 'description="%s"\n' "${4:-$1}"
    printf 'command="%s"\n' "$2"
    printf 'command_args="%s"\n' "$3"
    printf 'command_background="yes"\n'
    printf 'pidfile="/run/%s.pid"\n' "$1"
    printf '\ndepend() {\n    need net\n}\n'
}

# -- Operations --------------------------------------------------------
# ois_service_install APP  (conf already loaded; binary path in meta)
ois_service_install() {
    _si_app="$1"
    _si_be="$(ois_service_backend)"
    if [ "$_si_be" = "none" ]; then
        ois_warn "no supported init system detected -- service registration skipped"
        ois_info "supported: systemd, launchd, OpenRC"
        return 0
    fi
    if [ "$_si_be" = "openrc" ] && [ "$OIS_SCOPE" != "system" ]; then
        ois_warn "OpenRC has no per-user services -- install with --system to register"
        return 0
    fi
    _si_bin="$(ois_meta_get "$_si_app" binary)" || return 1
    _si_args="$(ois_conf_expand "${OIS_SVC_ARGS:-}")"
    _si_unit="$(_ois_svc_unit_path "$_si_app")"

    case "$_si_be" in
        systemd)
            _ois_svc_gen_systemd "$_si_app" "$_si_bin" "$_si_args" \
                "$OIS_SVC_DESC" "$OIS_SVC_RESTART" "$OIS_SVC_AFTER" | \
                ois_write_atomic "$_si_unit" 644 || return 1
            _ois_systemctl daemon-reload || :
            _ois_systemctl enable "$_si_app.service" >/dev/null 2>&1 || \
                ois_warn "systemctl enable failed"
            _ois_systemctl start "$_si_app.service" || {
                ois_fail E-HOOK "service failed to start" \
                    "systemctl start $_si_app returned nonzero" \
                    "inspect: $( [ "$OIS_SCOPE" = system ] && printf 'journalctl -u %s' "$_si_app" || printf 'journalctl --user -u %s' "$_si_app")"
                return 1
            } ;;
        launchd)
            _ois_svc_gen_launchd "$_si_app" "$_si_bin" "$_si_args" \
                "$OIS_SVC_DESC" "$OIS_SVC_RESTART" | \
                ois_write_atomic "$_si_unit" 644 || return 1
            _ois_svc_ctl launchctl unload "$_si_unit" >/dev/null 2>&1 || :
            _ois_svc_ctl launchctl load "$_si_unit" || {
                ois_fail E-HOOK "launchctl load failed" "" \
                    "inspect: launchctl print com.ois.$_si_app"
                return 1
            } ;;
        openrc)
            _ois_svc_gen_openrc "$_si_app" "$_si_bin" "$_si_args" \
                "$OIS_SVC_DESC" | ois_write_atomic "$_si_unit" 755 || return 1
            _ois_svc_ctl rc-update add "$_si_app" default >/dev/null 2>&1 || \
                ois_warn "rc-update add failed"
            _ois_svc_ctl rc-service "$_si_app" start || {
                ois_fail E-HOOK "rc-service start failed" "" \
                    "inspect: rc-service $_si_app status"
                return 1
            } ;;
    esac

    ois_manifest_add "$_si_app" file "$_si_unit" purge
    ois_meta_setmany "$_si_app" <<EOF
service_backend=$_si_be
service_unit=$_si_unit
service_registered=1
EOF
    ois_ok "service registered ($_si_be): $_si_unit"
    return 0
}

ois_service_registered() {
    [ "$(ois_meta_get "$1" service_registered 2>/dev/null)" = "1" ]
}

ois_service_stop() {
    _ss_app="$1"
    ois_service_registered "$_ss_app" || return 0
    case "$(ois_meta_get "$_ss_app" service_backend)" in
        systemd) _ois_systemctl stop "$_ss_app.service" 2>/dev/null || : ;;
        launchd) _ois_svc_ctl launchctl unload \
                     "$(ois_meta_get "$_ss_app" service_unit)" 2>/dev/null || : ;;
        openrc)  _ois_svc_ctl rc-service "$_ss_app" stop 2>/dev/null || : ;;
    esac
    ois_dbg "service stopped: $_ss_app"
    return 0
}

ois_service_start() {
    _st_app="$1"
    ois_service_registered "$_st_app" || return 0
    case "$(ois_meta_get "$_st_app" service_backend)" in
        systemd) _ois_systemctl start "$_st_app.service" ;;
        launchd) _ois_svc_ctl launchctl load \
                     "$(ois_meta_get "$_st_app" service_unit)" ;;
        openrc)  _ois_svc_ctl rc-service "$_st_app" start ;;
    esac
}

ois_service_remove() {
    _sr_app="$1"
    ois_service_registered "$_sr_app" || return 0
    _sr_unit="$(ois_meta_get "$_sr_app" service_unit 2>/dev/null)" || _sr_unit=""
    case "$(ois_meta_get "$_sr_app" service_backend)" in
        systemd)
            _ois_systemctl stop "$_sr_app.service" 2>/dev/null || :
            _ois_systemctl disable "$_sr_app.service" >/dev/null 2>&1 || :
            if [ -n "$_sr_unit" ]; then ois_rm "$_sr_unit"; fi
            _ois_systemctl daemon-reload 2>/dev/null || : ;;
        launchd)
            if [ -n "$_sr_unit" ]; then
                _ois_svc_ctl launchctl unload "$_sr_unit" 2>/dev/null || :
                ois_rm "$_sr_unit"
            fi ;;
        openrc)
            _ois_svc_ctl rc-service "$_sr_app" stop 2>/dev/null || :
            _ois_svc_ctl rc-update del "$_sr_app" default >/dev/null 2>&1 || :
            if [ -n "$_sr_unit" ]; then ois_rm "$_sr_unit"; fi ;;
    esac
    ois_ok "service unregistered"
    return 0
}

ois_service_status() {
    _sv_app="$1"
    ois_service_registered "$_sv_app" || { printf 'not-registered\n'; return 3; }
    case "$(ois_meta_get "$_sv_app" service_backend)" in
        systemd) _ois_systemctl status "$_sv_app.service" ;;
        launchd) _ois_svc_ctl launchctl print "com.ois.$_sv_app" ;;
        openrc)  _ois_svc_ctl rc-service "$_sv_app" status ;;
    esac
}
