app_name     = ytcui
binary       = ytcui
display_name = ytcui
github       = MilkmanAbi/ytcui

# next_best_version = yes  # if exact dep version missing, try nearest available
# next_best_version = no   # (default) fail fast with clear message

[build]
system = make
out    = ytcui

[deps]
ncurses
curl
openssl >= 1.0

[deps.optional]
chafa
mpv.cmd = mpv

[owns]
config = $XDG_CONFIG_HOME/ytcui
data   = $XDG_DATA_HOME/ytcui
cache  = $XDG_CACHE_HOME/ytcui
